// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyTracker.Infrastructure.Persistence;
using Pomelo.EntityFrameworkCore.MySql.Metadata;

#nullable disable

namespace MoneyTracker.Infrastructure.Migrations.MySql
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20250822211049_AddUploadedFileEntity")]
    partial class AddUploadedFileEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MoneyTracker.Domain.Entities.UploadedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasCollation("ascii_general_ci");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("char(36)")
                        .HasCollation("ascii_general_ci");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<string>("ExtractedDataJson")
                        .HasColumnType("longtext")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("longtext")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProcessingMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.ComputedColumn);

                    b.Property<DateTime?>("StatementPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StatementPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("char(36)")
                        .HasCollation("ascii_general_ci");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasCollation("ascii_general_ci");

                    b.Property<DateTime?>("VirusScanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VirusScanResult")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasCollation("utf8mb4_0900_ai_ci");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FileType")
                        .HasDatabaseName("IX_UploadedFiles_FileType");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_UploadedFiles_Status");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("IX_UploadedFiles_TransactionId");

                    b.HasIndex("UploadDate")
                        .HasDatabaseName("IX_UploadedFiles_UploadDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UploadedFiles_UserId");

                    b.HasIndex("UserId", "FileType")
                        .HasDatabaseName("IX_UploadedFiles_UserId_FileType");

                    b.ToTable("UploadedFiles", (string)null);

                    b.HasAnnotation("MySql:CharSet", "utf8mb4");
                });
#pragma warning restore 612, 618
        }
    }
}
